import java.util.ArrayList;
import java.util.Arrays;

public class Verbos {
	final static ArrayList<String> Verbos= new ArrayList (Arrays.asList(
			"Header",	
			"Pre_Login_Paso_0_1",	
			"Pre_Login_Paso_0_2",	
			"Pre_Login_Paso_1_1_Ok",	
			"Pre_Login_Paso_1_2",	
			"Pre_Login_Paso_2",	
			"Pre_Login_Paso_3_Ok",	
			"Pre_Login_Paso_3_Fallido",	
			"Primer_Login",	
			"Login",	
			"Cambio_Clave",	
			"Consolidado_Productos",	
			"Consulta_Movimientos_Cuenta_Vista",	
			"Detalle_Movimiento_Cuenta_Vista",	
			"Envio_Detalle_Movimiento_Cuenta_Vista",	
			"Consulta_CBU",	
			"Envio_CBU",	
			"Consulta_Agenda",	
			"Transferencia_Cuentas_Propias",	
			"Transferencia_Terceros",	
			"Compra_Divisa",	
			"Venta_Divisa",	
			"Cotiza_Divisa",	
			"Consulta_Resumen_Tarjeta",	
			"Envio_Resumen_Tarjeta_Master",	
			"Consulta_Movimientos_Tarjeta",	
			"Consulta_Autorizaciones_Tarjeta",	
			"Consulta_Cuota_Pendientes_Tarjeta",	
			"Consolidado_Inversiones",	
			"Consolidado_Plazo_Fijo",	
			"Detalle_Imposicion",	
			"Simulacion_Imposicion",	
			"Consolidado_Fondos",	
			"Detalle_Tenencia_Fondos",	
			"Consolidado_Custodia",	
			"Detalle_Tenencia_Custodia",	
			"Consolidado_Pago_Servicios",	
			"Pago_Servicios_Factura",	
			"Pago_Servicios_Tarjeta",	
			"Pago_Servicios_Celular",	
			"Consulta_Pagos_Realizados",	
			"Envio_Comprobante_Factura",	
			"Envio_Comprobante_Tarjeta",	
			"Envio_Comprobante_Celular",	
			"Envio_Comprobante_Transferencia",	
			"Envio_Comprobante_Pagos",	
			"Detalle_Pagos_Realizados",	
			"Consulta_Eresumen",	
			"Alta_Eresumen",	
			"Baja_Eresumen",	
			"Solicitud_Producto",	
			"Consulta_Telefonos",	
			"Visualizar_Mensajes",	
			"Me_Interesa_Mensaje",	
			"No_Me_Interesa_Mensaje",	
			"Recomendar_Aplicacion",	
			"Consulta_Contenido",	
			"ENVIO_COMENTARIO",	
			"SALDO_AL_3112",	
			"ENVIO_SALDO_AL_3112",	
			"Codigo_Referido_Generado",	
			"Codigo_Referido_Usado",	
			"Alta_Caja_Ahorro",	
			"Alta_Tarjeta_Adicional",	
			"Alta_Plazo_Fijo",	
			"Renovar_Plazo_Fijo",	
			"Acreditar_Plazo_Fijo",	
			"Baja_Alias",	
			"Modificacion_Alias",	
			"Reasignar_Alias",	
			"Nuevo_Alias",	
			"Rescatar_Fondo",	
			"Comparar_Fondo",	
			"Suscribir_Fondo",	
			"Ver_Grafico_Fondo",	
			"Consulta_Detalle_Fondo",	
			"Test_Inversor_Fondo",	
			"Alta_Inversor_Fondo",	
			"Consulta_Inver_Prog",	
			"Alta_Inver_Prog",	
			"Consulta_FAQ_Fondo",	
			"Validar_Factor_Tarjeta_Coord",	
			"Cliente_Sin_Factor",	
			"Registrar_Biometria",	
			"Eliminar_Biometria",	
			"Registrar_Dispositivo",	
			"Eliminar_Dispositivo",	
			"Actualizar_Prueba_De_Vida",	
			"Listar_Dispositivos",	
			"Login_Biometria",	
			"Alta_Viaje",	
			"Consulta_Visajes_Guardados",	
			"Eliminar_Viaje",	
			"Modificar_Viaje",	
			"DEBIN_Consulta_Pendientes",	
			"DEBIN_Autorizar_Orden",	
			"DEBIN_Rechazar_Orden",	
			"DEBIN_Consultar_Historico_Recibidos",	
			"DEBIN_Adherir_Cuenta",	
			"DEBIN_Generar_Orden",	
			"DEBIN_Eliminar_Orden",	
			"DEBIN_Consultar_Ordenes_Generadas",	
			"DEBIN_Consultar_Historico_Emitidos",	
			"DEBIN_Desvincular_Cuenta",	
			"DEBIN_Consulta_Especifica",	
			"Alta_Viaje",	
			"Consulta_Visajes_Guardados",	
			"Eliminar_Viaje",	
			"Modificar_Viaje",	
			"Novedad_No_Autenticado_Continuar",	
			"Novedad_No_Autenticado_Omitir",	
			"Novedad_Entendi",	
			"Novedad_Saber_Mas",	
			"Novedad_Ver",	
			"Alta_TAM",	
			"Liberar_TAM",	
			"Consultar_TAM",	
			"Eliminar_TAM",	
			"formatData"));	

			final static String TransferenciaCuentasPropias = "Transferencia_Cuentas_Propias";
			final static String TransferenciaTerceros = "Transferencia_Terceros";
			final static String PafoServiciosFactura = "Pago_Servicios_Factura";
			final static String PagoServiciosTarjeta = "Pago_Servicios_Tarjeta";
			final static String PagoServiciosCelular = "Pago_Servicios_Celular";
			final static String AltaPlazoFijo = "Alta_Plazo_Fijo";
			final static String RenovarPlazoFijo = "Renovar_Plazo_Fijo";
			final static String CompraDivisa = "Compra_Divisa";
			final static String VentaDivisa = "Venta_Divisa";
			final static String AltaTam = "Alta_TAM";
			final static String LiberarTam = "Liberar_TAM";
			final static String DebinAutorizarOrden = "DEBIN_Autorizar_Orden";
			final static String DebinGenerarOrden = "DEBIN_Generar_Orden";
			
			final static ArrayList<String> VerbosConImporte = new ArrayList<String>(Arrays.asList(TransferenciaCuentasPropias, TransferenciaTerceros, PafoServiciosFactura, 
					PagoServiciosTarjeta, PagoServiciosCelular, AltaPlazoFijo, RenovarPlazoFijo, CompraDivisa, VentaDivisa, AltaTam, LiberarTam,
					DebinAutorizarOrden, DebinGenerarOrden));
}
